In [1]:
import numpy as np

# 创建数组

In [10]:
score = np.array([[76, 87, 90, 67, 89],
        [86, 85, 91, 92, 93],
        [66, 77, 68, 59, 98],
        [82, 80, 70, 71, 79],
        [81, 90, 88, 63, 59],
        [69, 78, 90, 99, 78],
        [91, 92, 59, 51, 85],
        [63, 69, 76, 79, 81]])

In [11]:
score

array([[76, 87, 90, 67, 89],
       [86, 85, 91, 92, 93],
       [66, 77, 68, 59, 98],
       [82, 80, 70, 71, 79],
       [81, 90, 88, 63, 59],
       [69, 78, 90, 99, 78],
       [91, 92, 59, 51, 85],
       [63, 69, 76, 79, 81]])

# 数组相关属性

In [12]:
score.shape

(8, 5)

In [13]:
score.ndim

2

In [14]:
score.size

40

In [15]:
score.itemsize

4

In [16]:
score.dtype

dtype('int32')

# 数组形状

In [17]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [18]:
b = np.array([[1, 2, 3],[2, 3, 4]])
b

array([[1, 2, 3],
       [2, 3, 4]])

In [20]:
c = np.array([[[1, 2, 3],[2, 3, 4]],[[3, 4, 5],[4, 5, 6]]])
c

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]]])

In [21]:
c.ndim

3

In [23]:
c.dtype

dtype('int32')

In [24]:
d = np.array([1, 2, 3],dtype = np.float64)
d

array([1., 2., 3.])

In [25]:
d.dtype

dtype('float64')

In [26]:
e = np.array(['I','love','python'],dtype = np.string_)
e

array([b'I', b'love', b'python'], dtype='|S6')