In [1]:
import torch

# 数据操作

In [2]:
x = torch.arange(12)
x  # 向量

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape   # 维度

torch.Size([12])

In [4]:
x.numel()   # 元素的种类

12

In [5]:
x.reshape((3,4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.tensor([[2,3,4],[1,2,3],[7,8,9]]).shape     # 通过python列表创建张量数组

torch.Size([3, 3])

In [8]:
# 进行
x = torch.tensor([1,2,4,7,9.0])    
y = torch.tensor([1,4,6,7,9])         
x+y, x-y, x*y, x/y, x**y                          #算术运算符（+，-，*，/，**）

(tensor([ 2.,  6., 10., 14., 18.]),
 tensor([ 0., -2., -2.,  0.,  0.]),
 tensor([ 1.,  8., 24., 49., 81.]),
 tensor([1.0000, 0.5000, 0.6667, 1.0000, 1.0000]),
 tensor([1.0000e+00, 1.6000e+01, 4.0960e+03, 8.2354e+05, 3.8742e+08]))

In [9]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[1,2,3,4],[2.0,4,5,6],[8,9,9,7]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 2.,  4.,  5.,  6.],
         [ 8.,  9.,  9.,  7.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  2.,  4.,  5.,  6.],
         [ 8.,  9., 10., 11.,  8.,  9.,  9.,  7.]]))

In [10]:
X==Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True, False, False]])

In [11]:
X.sum()

tensor(66.)

In [12]:
# 广播机制进行元素操作  维度一样
x = torch.arange(3).reshape((3,1))
y = torch.arange(2).reshape((1,2))
x,y

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [13]:
x+y

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [14]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [15]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
# 运行一些操作会导致新结果分配内存
before = id(Y)
Y = Y+X
id(Y) == before

False

In [17]:
# 原地操作
Z = torch.zeros_like(Y)
print('id(Z)',id(Z))
Z[:] = Y+X
print('id(Z)',id(Z))

id(Z) 2415044108720
id(Z) 2415044108720


In [18]:
before = id(X)
X += Y
id(X) == before

True

In [19]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [20]:
a = torch.tensor([3.5])
a, a.item(), float(a)

(tensor([3.5000]), 3.5, 3.5)

# 数据处理

In [21]:
import os

In [22]:
# 创建一个人工数据集，并存储在csv（逗号分隔符）文件 ../data/house_tiny.csv中。以其他格式存储的数据也可以通过类似的方式进行处理
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms, Alley, Price\n')  #列名
    f.write('NA, Pave, 127500\n')   # 每行表示一个数据样本
    f.write('2, NA, 106000\n') 
    f.write('4, NA, 178100\n')
    f.write('NA, NA, 140000\n')
data_file

'..\\data\\house_tiny.csv'

In [23]:
import pandas as pd 

In [24]:
data = pd.read_csv(data_file)
data

NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0     NA  106000
2       4.0     NA  178100
3       NaN     NA  140000

In [25]:
# 通过位置索引iloc，我们将data分成inputs和outputs， 其中前者为data的前两列，而后者为data的最后一列。 对于inputs中缺少的数值，我们用同一列的均值替换“NaN”项
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  Alley
0       3.0   Pave
1       2.0     NA
2       4.0     NA
3       3.0     NA


C:\Users\h2220\AppData\Local\Temp\ipykernel_17488\961750372.py:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  inputs = inputs.fillna(inputs.mean())


In [26]:
# 对于inputs中的类别值或离散值，我们将“NaN”视为一个类别。 由于“巷子类型”（“Alley”）列只接受两种类型的类别值“Pave”和“NaN”， pandas可以自动将此列转换为两列“Alley_Pave”和“Alley_nan”。 巷子类型为“Pave”的行会将“Alley_Pave”的值设置为1，“Alley_nan”的值设置为0。 缺少巷子类型的行会将“Alley_Pave”和“Alley_nan”分别设置为0和1
inputs1 = pd.get_dummies(inputs, dummy_na=True)
print(inputs1)

   NumRooms   Alley_ NA   Alley_ Pave   Alley_nan
0       3.0           0             1           0
1       2.0           1             0           0
2       4.0           1             0           0
3       3.0           1             0           0


In [27]:
inputs2 = pd.get_dummies(inputs)
print(inputs2)

   NumRooms   Alley_ NA   Alley_ Pave
0       3.0           0             1
1       2.0           1             0
2       4.0           1             0
3       3.0           1             0


In [28]:
X, Y = torch.tensor(inputs2.values), torch.tensor(outputs.values)
X,Y

(tensor([[3., 0., 1.],
         [2., 1., 0.],
         [4., 1., 0.],
         [3., 1., 0.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

# 线性代数

In [29]:
A = torch.arange(20).reshape((5,4))
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [30]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [31]:
# 对称矩阵
B = torch.tensor([[1,2,3],[2,0,4],[3,4,0]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [32]:
A = torch.arange(20, dtype = torch.float32).reshape((5,4))
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [33]:
id(A),id(A+B),id(B)

(2415055510544, 2415055508304, 2415055506064)

In [34]:
# 两个矩阵的按元素乘法称为Hadamard积（Hadamard product）（数学符号）
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [35]:
# 将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
a = 2
a + A, a*A

(tensor([[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [36]:
A.shape

torch.Size([5, 4])

In [37]:
A = torch.arange(20*2, dtype = torch.float32).reshape((2, 5, 4))
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [38]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [39]:
A_sum_axis0 = A.sum(axis=0)   # 对第一个维度求和，其他维不变
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [40]:
A_sum_axis1 = A.sum(axis=1)   # 对第二个维度求和，其他维不变
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [41]:
A_sum_axis2 = A.sum(axis=2)   # 对第三个维度求和，其他维不变
A_sum_axis2, A_sum_axis2.shape

(tensor([[  6.,  22.,  38.,  54.,  70.],
         [ 86., 102., 118., 134., 150.]]),
 torch.Size([2, 5]))

In [42]:
A.sum(axis=[0, 1])

tensor([180., 190., 200., 210.])

In [43]:
# 求均值，相当于先求和再/元素个数
A.mean(), A.sum() / A.numel()  

(tensor(19.5000), tensor(19.5000))

In [44]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [45]:
# 有时在调用函数来计算总和或均值时保持轴数不变会很有用。
sum_A = A.sum(axis = 1, keepdims = True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [46]:
# 例如：由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A。
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [47]:
# 如果我们想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），我们可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度
A.cumsum(axis=1)

tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   6.,   8.,  10.],
         [ 12.,  15.,  18.,  21.],
         [ 24.,  28.,  32.,  36.],
         [ 40.,  45.,  50.,  55.]],

        [[ 20.,  21.,  22.,  23.],
         [ 44.,  46.,  48.,  50.],
         [ 72.,  75.,  78.,  81.],
         [104., 108., 112., 116.],
         [140., 145., 150., 155.]]])

In [48]:
# 另一个最基本的操作之一是点积。 给定两个向量， 它们的点积（dot product） （或） 是相同位置的按元素乘积的和：
y = torch.ones(4,dtype = torch.float32)
x = torch.tensor([0., 1., 2., 3.])
x, y, torch.dot(x, y),torch.sum(x*y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

In [49]:
# 矩阵向量乘积，其中每个ai都是行向量，表示矩阵的第i行。 A为m*n的矩阵，x为n维列向量，矩阵向量积Ax是一个长度为m的列向量， 其第i个元素是点积ai·x
A1 = torch.arange(20,dtype = torch.float32).reshape((5,4))
A1, x, A1.shape, x.shape,torch.mv(A1,x) 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [50]:
# 矩阵-矩阵乘法,用行向量ai表示矩阵A1的第i行，并让列向量bj作为矩阵B的第j列。要生成矩阵积C = A·B，最简单的方法是考虑的行向量和的列向量:每个元素cij计算为行向量ai与列向量bj点积
B = torch.ones((4,3))
A1, B, torch.mm(A1,B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [51]:
# L2 范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [52]:
# L1范数
torch.abs(u).sum()

tensor(7.)

In [53]:
# 矩阵F范数
torch.norm(torch.ones((4,9)))

tensor(6.)

# 自动求导

In [54]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [55]:
# 在计算y关于x的梯度之前，我们需要一个地方来储存梯度
x.requires_grad_(True)   # 等价于 x = torch.arange(4.0, requires_grad = True)
x.grad  # 默认值是None

In [56]:
y = 2 * torch.dot(x, x)  # 内积
y

tensor(28., grad_fn=<MulBackward0>)

In [57]:
# 调用反向传播函数来自动计算y关于x每个分量的梯度
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [58]:
x.grad == x * 4

tensor([True, True, True, True])

In [59]:
#  在默认情况下，pytorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [60]:
# 对非标量调用‘backward’需要传入一个‘gradient’参数，该参数指定微分函数
x.grad.zero_()
y = x*x   # 矩阵
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [61]:
# 将某些计算移动到记录的计算图之外
x.grad.zero_()
y = x*x
u = y.detach()   #将y变为一个常数赋予u
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [62]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [63]:
# 即使构建函数的计算图需要通过Python控制流（例如，条件、循环或任意函数调用），我们仍然可以计算得到的变量的梯度
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size = (),requires_grad=True)
d = f(a)
d.backward()
a.grad == d/a

tensor(True)